### ISSUE TITLE
Some icons are missing on GNOME desktop

### ISSUE THREAD

**Issue by USBA** [OrancheloTeam/oranchelo-icon-theme#11]
Please check this screenshot
![screenshot from 2016-09-23 16-32-43](https://cloud.githubusercontent.com/assets/19838220/18783837/e02ab516-81ab-11e6-9c5d-4dcc99f3144f.png)

**Missing icons:**
Cheese
Clocks
Documents
Maps
Text Editor (Gedit)
Weather

**Comment by Madh93** [comment]
Many of that missing icons are in Oranchelo. What version of Oranchelo have you installed? Try to reinstall it:

    sudo apt remove oranchelo-icon-theme
    sudo apt install oranchelo-icon-theme

**Comment by USBA** [comment]
I installed the latest version of Oranchelo (v7.4)

**Comment by USBA** [comment]
apt commands are not working on this. This is Fedora 24
Just download and extracted to home/.icons

**Comment by Madh93** [comment]
Okey, let me try it on Fedora 24 :smile:

**Comment by USBA** [comment]
Yeah! I found icon names of these missing icons.

Text editor:  `gedit`
Characters: `gnome-characters`
Clocks: `org.gnome.clocks`
Cheese: `org.gnome.Cheese`
Documents: `org.gnome.Documents`
Maps: `org.gnome.Maps`
Weather: `org.gnome.weather`

![screenshot from 2016-09-23 17-59-50](https://cloud.githubusercontent.com/assets/19838220/18785736/949ce89c-81b7-11e6-9d9f-99e89ca720da.png)

**Comment by Madh93** [comment]
Thank you for the icon names, I guess the solution is add symbolic links to base icon names in Oranchelo.

@zayronxio what do you think?

**Comment by USBA** [comment]
@Madh93 @zayronxio 
Download these missing icons
https://drive.google.com/open?id=0BywiiYFzILRIdzlEUWZiTmU5VXc

**Comment by USBA** [comment]
@zayronxio 
I'm waiting for your new places icons. Please hurry up!

**Comment by USBA** [comment]
@Madh93 
Check out chis
https://www.gnome-look.org/p/1151321/

Look at new places icons
![oranchelo4](https://cloud.githubusercontent.com/assets/19838220/20506729/01b18832-b07c-11e6-920b-7595d0efbd31.png)

Is it good?

**Comment by Madh93** [comment]
@USBA i like it but this decision take @zayronxio
