### ISSUE TITLE
Missing icons on Pantheon (elementary OS)

### ISSUE THREAD

**Issue by henriquearthur** [OrancheloTeam/oranchelo-icon-theme#13]
I use elementary OS Freya, which uses Pantheon Desktop Environment.

I installed Oranchelo but icons on notifications are missing, as you can see below (should be a volume icon and a wifi icon in the notifications).

I've compared icons'  name from Oranchelo and the default icons theme, and they have the same names.

Default icons and other icon themes display volume and wifi icon in the notifications below.

![captura de tela de 2016-09-23 18 12 27](https://cloud.githubusercontent.com/assets/5016325/18811642/8c817048-828d-11e6-95c9-fe721526b6a6.png)

**Comment by Madh93** [comment]
Okey, let me try it on Elementary :+1:

**Comment by afrozalm** [comment]
I'm using elementary OS loki and many icons are missing in my system too.

**Comment by Madh93** [comment]
| Distro | Desktop | Name | Icon |  Status |
|---|---|---|---|---|
| Elementary OS Freya/Loki | Pantheon  |   |  | :exclamation:  |
| Elementary OS Freya/Loki | Pantheon  |   |  | :exclamation:  |
| Elementary OS Freya/Loki | Pantheon  |   |  | :exclamation:  |
| Elementary OS Freya/Loki | Pantheon  |   |  | :exclamation:  |
| Elementary OS Freya/Loki | Pantheon  |   |  | :exclamation:  |

**Comment by Madh93** [comment]
| Distro | Desktop | Name | Icon |  Status |
|---|---|---|---|---|
| Elementary OS Freya/Loki | Pantheon  | cerbere  | view-refresh | :exclamation:  |
| Elementary OS Freya/Loki | Pantheon  | wingpanel | wingpanel | :exclamation:  |
| Elementary OS Freya/Loki | Pantheon  | pantheon-parental-controls-client | preferences-system-parental-controls | :exclamation:  |
| Elementary OS Freya/Loki | Pantheon  | screenshoot | accessories-screenshot | :exclamation:  |

**Comment by DroWnThePoor** [comment]
I'm on Freya, and I'm also missing the ones listed above. But additionally I'm missing:
Geary:
      Mark Conversation
      Move Conversation
Photos(Shotwell):
       Adjust Photo's Color & Tone
       Automatically Improve Photo's Appearance

![oranchellomissing](https://cloud.githubusercontent.com/assets/16339020/20690652/de9719d4-b599-11e6-81a3-07e0c649599f.png)

**Comment by yanike** [comment]
Should this be closed?

**Comment by henriquearthur** [comment]
@yanike I don't use Oranchelo or elementary anymore so I don't know if the bugs are still there.
