### ISSUE TITLE
Update versión to Fedora 24

### ISSUE THREAD

**Issue by fjospinas** [OrancheloTeam/oranchelo-icon-theme#14]
Fedora is currently in version 24, therefore the SPEC file has to be run in this version so that the final rpm contains x.fc24.noarch.rpm

**Comment by Madh93** [comment]
Thanks, I will update today.

**Comment by Madh93** [comment]
Yet available: https://github.com/OrancheloTeam/oranchelo-icon-theme/releases/tag/v0.7.4
