### ISSUE TITLE
Icon request: Blockify, GNOME Builder, Messenger, OpenRA, Spyder, SuperTux, Valama and Visual Studio Code

### ISSUE THREAD

**Issue by fusion809** [OrancheloTeam/oranchelo-icon-theme#15]
Hi,

I'd like to request icons for:
- Blockify (icon name: `blockify`)
- GNOME Builder (icon name: `builder`)
- Messenger (icon name: `messengerfordesktop`)
- OpenRA (icon name: `openra`)
- Spyder (icon name: `spyder`)
- Spyder3 (icon name: `spyder3`)
- SuperTux (icon name: `supertux`)
- Valama (icon name: `valama`)
- Visual Studio Code (icon name: `visual-studio-code`, `code-oss`, `code`)

Thanks for your time,
Brenton

**Comment by joaoeudes7** [comment]
Visual Studo Code Insiders too Please :)

**Comment by zayronxio** [comment]
added icons
