### ISSUE TITLE
Evolution: wrong icon size 

### ISSUE THREAD

**Issue by dirosis** [OrancheloTeam/oranchelo-icon-theme#16]
I found out this issue: when  adding a new account on evolution, the side bar icon of calendar appears a little bit bigger than it should. The result is quite funny:
![evol](https://cloud.githubusercontent.com/assets/24278145/20766319/abd7e3ce-b73e-11e6-8fac-7780332b05fb.png)
I thing that may be a problem in other similar situations but I can't find any.

Thank you for your time!
P.S. I love oranchelo

**Comment by Madh93** [comment]
OMG 😆 

This happens only using Oranchelo? Have you tried this action using another icon theme?

**Comment by dirosis** [comment]
It does not happen with adwaita but I can't know what happens with other not gnome-official icon sets as the only one I have installed is oranchelo.

**Comment by zayronxio** [comment]
If the same problem occurs again please open a new one issues
