### ISSUE TITLE
Is there a plan for seperate Dark and Light icon themes?

### ISSUE THREAD

**Issue by JackieMium** [OrancheloTeam/oranchelo-icon-theme#25]
I personally love this icon theme VERY MUCH. 
But notification icons(such as WiFi icon, volume icon and battery icon) on the XFCE4 panel in this package are in white, which makes it really hard to see as I am using a semi-transparent panel already. 
I am not into using a DARK panel, so, is it possible that you will provide seperate Dark and Light icon themes?

Best regards.
Jackie

**Comment by zayronxio** [comment]
yes, but that will take some time more
