### ISSUE TITLE
Odd window handles on Ubuntu 17.10

### ISSUE THREAD

**Issue by envygeeks** [OrancheloTeam/oranchelo-icon-theme#26]
![screenshot-2017-10-31_08-44-03](https://user-images.githubusercontent.com/99763/32226898-cc3d2404-be17-11e7-913a-d32966319dfb.png)

**Comment by envygeeks** [comment]
It seems this might be intended, but on 17.10 it's very much noticeable.  I never noticed on 16.04.

**Comment by marathone** [comment]
I don't see anything in your image that is amiss.

**Comment by envygeeks** [comment]
You aren't very good at design then.

**Comment by marathone** [comment]
¯\_( ͡° ͜ʖ ͡°)_/¯  Well thanks young man, such a constructive response.

**Comment by zayronxio** [comment]
this repository is only from the icon pack, which does not affect the appearance of the window manager

**Comment by envygeeks** [comment]
Do what? This mentioned window handles, of which you literally control with this https://github.com/OrancheloTeam/oranchelo-icon-theme/blob/755d355bdae7620d1c1a6bbf8005b7aa66c69c5d/Oranchelo/actions/scalable/window-minimize.svg

**Comment by zayronxio** [comment]
I guess then it's a problem that is inherited from super flat remix.

I will make the correction and we will see if it changes,
Thank you

**Comment by zayronxio** [comment]
try now
