### ISSUE TITLE
Calendar icon

### ISSUE THREAD

**Issue by yanike** [OrancheloTeam/oranchelo-icon-theme#28]
Hi. Love your icon theme!

I've noticed that the calendar icon was not modified. Can you please add a calendar icon :)

**Comment by zayronxio** [comment]
Maybe it's just a problem with the icon's name, soon I'll solve

**Comment by zayronxio** [comment]
Discuss what desktop and distro are you using?

**Comment by yanike** [comment]
Ubuntu 16.04 LTS

**Comment by zayronxio** [comment]
Will it be possible for you to investigate the name of the icon?
you can see it in usr / share / applications / calendar, (or the name of the calendar)
you open it with some text editor and you can see the icon's name

**Comment by zayronxio** [comment]
solved

**Comment by yanike** [comment]
The current Thunderbird icon would work PERFECT for Mailspring application. I'm using it now for it.

name: Mailspring
command-name: /usr/bin/mailspring %U
location: /usr/share/applications

Sent from Mailspring (https://link.getmailspring.com/link/1523815088.local-09031357-d131-v1.2.1-7e7447b6@getmailspring.com/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrMDA2MGYzYzhiNTdhOWFhZTgyM2U0ZmQwZGRiNDdjYTE5NjU4ODM2YzhjMzhhMjcyOTJjZjAwMDAwMDAxMTZjYzU1ODU5MmExNjljZTExYzg2MDFhQHJlcGx5LmdpdGh1Yi5jb20%3D), the best free email app for work
