### ISSUE TITLE
Icon requests?

### ISSUE THREAD

**Issue by stepedes** [OrancheloTeam/oranchelo-icon-theme#38]
_Im really sorry if this doesnt belong here but Im all cofused here._
Would you please make new Ramme(Instagram) and Messengerfordesktop icons to look similiar to the already implemented Twitter icon? I mean like a real messenger and instagram icon put to the style.
I tried using stock icons but they dont look alike.
Thanks

**Comment by zayronxio** [comment]
I will consider your proposal friend
