### ISSUE TITLE
VS Code Insider Icon

### ISSUE THREAD

**Issue by cubetastic33** [OrancheloTeam/oranchelo-icon-theme#39]
I really like this oranchelo icon theme, it's material design and the icons are interesting and new. However, there is one thing: You have an (amazing) icon for VSCode, but there doesn't seem to be one for VSCode Insiders edition. This makes it look kind of weird:
![image](https://user-images.githubusercontent.com/33519300/43358273-746de758-92ac-11e8-8664-f8b6e74b380a.png)
So, it would be really nice if you could make a similar icon for VS Code Insiders!

**Comment by cubetastic33** [comment]
Wonderful! Thanks a lot for adding this icon. Now it looks the two text editors look so much better together!
![image](https://user-images.githubusercontent.com/33519300/44335973-a4fd1f80-a493-11e8-9dee-34f42bef2698.png)

**Comment by zayronxio** [comment]
thanks for the report, this happens because I have not released a new version, once I launch it and upload it to ppa you can have it in an update,
