### ISSUE TITLE
Icon for Eddie AirVPN client missing.

### ISSUE THREAD

**Issue by cdysthe** [OrancheloTeam/oranchelo-icon-theme#42]
I am missing an icon for the Eddie AirVPN client: https://airvpn.org/linux/

> [Desktop Entry]
> Name=Eddie - OpenVPN GUI
> Comment=OpenVPN GUI with additional user-friendly features
> Exec=/usr/bin/eddie-ui
> Icon=/usr/share/pixmaps/eddie-ui.png
> Terminal=false
> Type=Application
> Categories=GNOME;Network

**Comment by zayronxio** [comment]
I regret that, however I can not fix it
