### ISSUE TITLE
Need a new version for Ubuntu 16.04

### ISSUE THREAD

**Issue by USBA** [OrancheloTeam/oranchelo-icon-theme#5]
There are lot of icons **without** oranchelo icons in Ubuntu 16.04 in Gnome desktop.
Therefor need a new version of this icon theme.
Thanks.

**Comment by Madh93** [comment]
Thank you for reporting this issue.

At this time i cannot guarantee the date for a new version, but will be considered.

**Comment by Madh93** [comment]
Can you list the name of missing icons?

**Comment by umayanga1** [comment]
Ok I'll list missing icons within 24 hours.
Thanks for respond.

**Comment by umayanga1** [comment]
Missing icons:
Books
Calendar
Cheese
Documents (This is an application. Not Documents folder)
Maps
ipython
Software (Gnome software center)
Sudoku
Text Editor
Weather
Xdiagnose
Browser (Ubuntu Web browser)

**Comment by umayanga1** [comment]
Please increase the height of folder icon, Desktop icon, Documents, Downloads, Music, Pictures, Public, Templates, Videos, Examples.

**Comment by umayanga1** [comment]
And also make HTML memitype icon in CSS memetype icon style.

**Comment by umayanga1** [comment]
Increase the colors (colours)

**Comment by umayanga1** [comment]
Increase the colors of icons. Because these icons look very light color.

**Comment by El-Zipo** [comment]
@Madh93 
Check these places icons
https://drive.google.com/open?id=0B0WWVqN0QQS-eTBGcHhXYlU0WUE

I think these icons are good for the the Oranchelo.

**Comment by Madh93** [comment]
Post your suggestion [here](https://www.facebook.com/groups/887649787956083/).

**Comment by zayronxio** [comment]
added icons
