### ISSUE TITLE
Some icons crash

### ISSUE THREAD

**Issue by khalegjr** [OrancheloTeam/oranchelo-icon-theme#57]
Hello, some icons are broken and during installation we have the following cache error: "gtk-update-icon-cache: The generated cache was invalid".
My system is a Manjaro with XFCE.
Here are some screens with broken icons.

![tela1](https://user-images.githubusercontent.com/35576198/80294124-780b1080-873c-11ea-83d1-e1cc8d17828f.png)
_Broken return, advance and top level icons._

![tela3](https://user-images.githubusercontent.com/35576198/80294184-1c8d5280-873d-11ea-94a9-97835ad54292.png)
_Error cache._

**Comment by khalegjr** [comment]
Hello, this error was resolved in the pull request #55.
Sorry for bothering. I'm closing the issue.
Thanks.

**Comment by jcuenod** [comment]
Wait, why did you close this issue when the PR isn't merged yet?

**Comment by khalegjr** [comment]
Hi! Yes, I closed the issue because it was replicated and the solution was committed in #55.
I don't know if the project is dead, but the last update was 4 months ago.
*Sorry about my English
