### ISSUE TITLE
Ubuntu Software icon is missing and ..........

### ISSUE THREAD

**Issue by USBA** [OrancheloTeam/oranchelo-icon-theme#7]
Ubuntu software icon is missing in the Unity desktop
It's Gnome software. But in Unity desktop, it's name is Ubuntu Software
Icon name:
ubuntusoftware.svg

And I really don't like the icon of the "Unity tweak tool"
Add the tweak tool icons of the "Papirus gtk icon theme"
![screenshot from 2016-08-14 22-22-32](https://cloud.githubusercontent.com/assets/19838220/17654135/a4d071ca-626d-11e6-9535-79ab28dfba53.png)

Increase the height of the places icons (ex: Documents, Downloads, Music, Videos, etc) and also increase the height of the floder icon.

Thanks.

**Comment by El-Zipo** [comment]
calender icon is missing

**Comment by Madh93** [comment]
`ubuntusoftware` and `unity-tweak` added.

There is a problem with `gnome-calendar` icon because calendar.desktop use other icon name. To fix this:

    sudo sed -i "s/Icon=.*/Icon=gnome-calendar/g" /usr/share/applications/org.gnome.Calendar.desktop
