### ISSUE TITLE
Gnome tweak tool

### ISSUE THREAD

**Issue by USBA** [OrancheloTeam/oranchelo-icon-theme#8]
Delete the "gnome-tweak-tool.svg" icon in the path "Oranchelo/categories/scalable"

Because that icon is showing as the icon of the Gnome tweak tool and gnome-tweak-tool icon in the "apps/scalable" is not showing as the icon of the gnome tweak tool.

Regards.

**Comment by zayronxio** [comment]
It has added a new icon for gnome-tweak-tool I hope that is your pleasure , thank you for comment

**Comment by El-Zipo** [comment]
@zayronxio 
I saw your new icons for tweak tools. They're really great.
But delete the tweak tool icon in the path "Oranchelo/categories/scalable/gnome-tweak-tool.svg" 
Because icon in that path is shown as the icon of the gnome tweak tool.

Thanks for the icon theme.

**Comment by zayronxio** [comment]
the change you solicitavas already been done , thanks for your support
